{% set name = "perl-extutils-makemaker" %}
{% set version = "7.78" %}
{% set sha256 = "43b33c20f8d82dba7cc48f8cd702f8fc9811e9d07880886dfd31b7077bd4a3a6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/B/BI/BINGOS/ExtUtils-MakeMaker-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    # So upstream XS-related tests can invoke a compiler.
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make  # [unix]
    - msys2-make  # [win]
  host:
    - perl {{ perl }}
  run:
    - perl

test:
  # Perl 'use' tests
  imports:
    - ExtUtils::Command
    - ExtUtils::Command::MM
    - ExtUtils::Liblist
    - ExtUtils::Liblist::Kid
    - ExtUtils::MM
    - ExtUtils::MM_AIX
    - ExtUtils::MM_Any
    - ExtUtils::MM_BeOS
    - ExtUtils::MM_Cygwin
    - ExtUtils::MM_DOS
    - ExtUtils::MM_Darwin
    - ExtUtils::MM_MacOS
    - ExtUtils::MM_NW5
    - ExtUtils::MM_OS2
    - ExtUtils::MM_QNX
    - ExtUtils::MM_UWIN
    - ExtUtils::MM_Unix
    - ExtUtils::MM_VMS
    - ExtUtils::MM_VOS
    - ExtUtils::MM_Win32
    - ExtUtils::MM_Win95
    - ExtUtils::MY
    - ExtUtils::MakeMaker
    - ExtUtils::MakeMaker::Config
    - ExtUtils::MakeMaker::Locale
    #- ExtUtils::MakeMaker::charstar
    - ExtUtils::MakeMaker::version
    - ExtUtils::MakeMaker::version::regex
    - ExtUtils::MakeMaker::version::vpp
    - ExtUtils::Mkbootstrap
    - ExtUtils::Mksymlists
    - ExtUtils::testlib

about:
  home: https://metacpan.org/release/ExtUtils-MakeMaker
  dev_url: https://github.com/Perl-Toolchain-Gang/ExtUtils-MakeMaker
  doc_url: https://metacpan.org/pod/ExtUtils::MakeMaker
  description: >
    ExtUtils::MakeMaker is the standard Perl toolchain module for turning module
    source into a Makefile (or equivalent) so distributions can be built and
    installed. It is widely used by CPAN and in-tree Perl extension builds.
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_family: OTHER
  license_file:
    - LICENSE
  summary: Create a module Makefile